version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
     - .env
    volumes:
      - ./:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: ./app.py
    ports:
     - "5000:5000"
    restart: always
